version: 2.1
jobs:
  build-sbcl:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Build
          command: sudo ./bootstrap.sh
      - store_artifacts:
          path: /home/circleci/project/sbcl/sbcl-2.2.1-WIP-x86-64-windows-binary.exe
          destination: sbcl-2.2.1-x86-64-windows-binary.exe
workflows:
  build-workflow:
    jobs:
      - build-sbcl
