name: build
on: [push]
env:
  SBCL_VERSION: 2.4.1
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: sudo sh -c "export SBCL_VERSION=$SBCL_VERSION && ./bootstrap.sh"
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          path: sbcl/sbcl-${{ env.SBCL_VERSION }}-x86-64-windows-binary.exe
          if-no-files-found: error
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: sbcl/sbcl-${{ env.SBCL_VERSION }}-x86-64-windows-binary.exe
          omitBody: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          tag: v${{ env.SBCL_VERSION }}
          commit: master
